[build]
builder = "railpack"

[deploy]
preDeployCommand = "php artisan storage:link && php artisan migrate --force"
healthcheckPath = "/login"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
